import { Artist, Post, Song, FrevoStep, HistoryEntry, MapPoint } from '@/types';

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'a1',
    name: 'Maestro Forró & OPBH',
    slug: 'maestro-forro',
    genre: 'Frevo Livre',
    bio: 'Regente, compositor e arranjador à frente da Orquestra Popular da Bomba do Hemetério, transformando o Frevo com fusões globais e energia visceral.',
    avatar_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    instagram_url: 'https://instagram.com',
    youtube_url: 'https://youtube.com',
    is_authorized_editor: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    followers_count: 1420,
    songs_count: 12,
  },
  {
    id: 'a2',
    name: 'SpokFrevo Orquestra',
    slug: 'spok-frevo-orquestra',
    genre: 'Frevo de Rua',
    bio: 'Liderada pelo saxofonista Spok, a orquestra eleva o Frevo de Rua instrumental ao circuito mundial do jazz e da música erudita.',
    avatar_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80',
    instagram_url: 'https://instagram.com',
    is_authorized_editor: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    followers_count: 3890,
    songs_count: 24,
  },
  {
    id: 'a3',
    name: 'Bloco da Saudade',
    slug: 'bloco-da-saudade',
    genre: 'Frevo de Bloco',
    bio: 'Fundado em 1974 para resgatar e preservar a tradição dos blocos líricos de pau e corda de Pernambuco com coral feminino e violões.',
    avatar_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80',
    instagram_url: 'https://instagram.com',
    is_authorized_editor: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    followers_count: 2150,
    songs_count: 18,
  },
  {
    id: 'a4',
    name: 'Claudionor Germano',
    slug: 'claudionor-germano',
    genre: 'Frevo Canção',
    bio: 'Patrimônio Vivo de Pernambuco, a voz imortal que gravou as maiores obras de Capiba e Nelson Ferreira por mais de sete décadas.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
    instagram_url: 'https://instagram.com',
    is_authorized_editor: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    followers_count: 5400,
    songs_count: 45,
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    author_id: 'u1',
    type: 'event',
    title: 'Acerto de Marcha no Recife Antigo',
    slug: 'acerto-de-marcha-recife-antigo',
    excerpt: 'Ensaio aberto dos blocos líricos e orquestras de frevo na Praça do Arsenal neste domingo.',
    content: 'O som dos metais e a magia dos corais líricos tomam conta do Bairro do Recife a partir das 16h. Traga sua sombrinha e venha celebrar a cultura viva!',
    cover_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    tags: ['Carnaval', 'RecifeAntigo', 'Ensaio'],
    status: 'published',
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: {
      id: 'u1',
      display_name: 'Paço do Frevo',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      role: 'admin',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    },
    likes_count: 148,
    comments_count: 23,
    is_liked: false,
  },
  {
    id: 'p2',
    author_id: 'u2',
    artist_id: 'a1',
    type: 'music',
    title: 'Lançamento de Nova Partitura: "Passo da Fervura"',
    slug: 'lancamento-partitura-passo-da-fervura',
    excerpt: 'Partitura completa para metais e percussão disponibilizada para orquestras e estudantes.',
    content: 'Partitura com arranjo inédito já disponível para download e consulta no catálogo cultural do FrevIA.',
    cover_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    tags: ['Partitura', 'FrevoDeRua', 'Metais'],
    status: 'published',
    published_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    artist: MOCK_ARTISTS[0],
    likes_count: 92,
    comments_count: 8,
    is_liked: true,
  },
  {
    id: 'p3',
    author_id: 'u3',
    type: 'news',
    title: 'Oficinas Gratuitas de Dança e Passo no Paço do Frevo',
    slug: 'oficinas-gratuitas-danca-paco-do-frevo',
    excerpt: 'Inscrições abertas para todas as idades aprenderem tesouras, ferrolho e pernada.',
    content: 'Aulas práticas semanais com mestres passistas tradicionais e contemporâneos de Pernambuco.',
    cover_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    tags: ['Dança', 'Passistas', 'Educação'],
    status: 'published',
    published_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: {
      id: 'u3',
      display_name: 'Escola de Frevo do Recife',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      role: 'admin',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    },
    likes_count: 210,
    comments_count: 34,
    is_liked: false,
  }
];

export const MOCK_SONGS: Song[] = [
  {
    id: 's1',
    artist_id: 'a1',
    title: 'Passo da Fervura',
    slug: 'passo-da-fervura',
    genre: 'Frevo Livre',
    description: 'Composição instrumental enérgica com diálogo virtuoso entre trompetes e saxofones.',
    lyrics: `(Instrumental — Frevo de Rua Fervente)
Entrada vibrante de trompetes em staccato.
Trombones respondem com contracanto sincopado.
A percussão acelera o andamento a 152 BPM.
O solo de saxofone alto corta a multidão em espiral.`,
    cover_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    score_path: 'scores/passo-da-fervura.pdf',
    score_is_private: false,
    status: 'published',
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    artist: MOCK_ARTISTS[0]
  },
  {
    id: 's2',
    artist_id: 'a3',
    title: 'Valores do Passado',
    slug: 'valores-do-passado',
    genre: 'Frevo de Bloco',
    description: 'Hino clássico que exalta a saudade dos antigos carnavais líricos e as serpentinas de Olinda.',
    lyrics: `Bloco das Flores, Vassourinhas
Prateado, Toureiros, Lenhadores
Batutas de São José
Tanta saudade dos velhos carnavais

Quando a orquestra entoava a canção
Toda a cidade cantava com emoção
E pelas ruas de pedra a brilhar
O frevo não parava de ecoar...`,
    cover_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80',
    score_path: 'scores/valores-do-passado.pdf',
    score_is_private: false,
    status: 'published',
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    artist: MOCK_ARTISTS[2]
  }
];

export const MOCK_STEPS: FrevoStep[] = [
  {
    id: 'st1',
    name: 'Tesoura',
    slug: 'tesoura',
    description: 'Um dos passos mais emblemáticos e dinâmicos do Frevo, com cruzamento rápido e rítmico das pernas.',
    instructions: '1. Inicie com os pés paralelos e joelhos semiflexionados.\n2. Cruze a perna direita pela frente da esquerda, apoiando a ponta do pé.\n3. Abra simultaneamente com um salto suave e cruze a perna esquerda pela frente.\n4. Mantenha a sombrinha em contrapeso girando na mão direita.',
    media_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    media_type: 'image',
    difficulty: 'Iniciante',
    category: 'Tradicional',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st2',
    name: 'Ferrolho',
    slug: 'ferrolho',
    description: 'Movimento ágil de agachamento e extensão lateral dos calcanhares simulando a trava de um ferrolho.',
    instructions: '1. Agache em posição de cócoras com equilíbrio na ponta dos pés.\n2. Estenda o calcanhar direito para o lado enquanto o tronco gira levemente.\n3. Recolha rapidamente e estenda a perna esquerda.\n4. Eleve a sombrinha acima da cabeça para estabilização visual.',
    media_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
    media_type: 'image',
    difficulty: 'Intermediário',
    category: 'Acrobático',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st3',
    name: 'Dobradiça',
    slug: 'dobradica',
    description: 'Flexão profunda e rápida dos joelhos para a frente enquanto os calcanhares sobem.',
    instructions: '1. Pés juntos na ponta.\n2. Lance os joelhos para frente mantendo as costas eretas.\n3. Retorne com impulso na cadência do dobrado do Frevo.',
    media_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80',
    media_type: 'image',
    difficulty: 'Avançado',
    category: 'Acrobático',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: 'h1',
    title: 'Origens e o Frever nas Ruas do Recife',
    slug: 'origens-do-frevo',
    period_label: 'Final do Século XIX',
    year_start: 1880,
    year_end: 1907,
    content: 'O Frevo nasce no final do século XIX da rivalidade entre as bandas militares e os capoeiras que protegiam os estandartes dos clubes de pedestres. O nome vem do verbo popular "frever" (ferver), expressando a efervescência popular.',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    source_text: 'Fundação Joaquim Nabuco & Paço do Frevo',
    source_url: 'https://pacodofrevo.org.br',
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'h2',
    title: 'A Primeira Menção Oficial na Imprensa',
    slug: 'primeira-mencao-1907',
    period_label: '9 de Fevereiro de 1907',
    year_start: 1907,
    year_end: 1907,
    content: 'O vocábulo "Frevo" é impresso pela primeira vez no Jornal Pequeno do Recife em 9 de fevereiro de 1907, data que se consagrou formalmente como o Dia do Frevo.',
    image_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80',
    source_text: 'Arquivo Histórico do Jornal Pequeno',
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'h3',
    title: 'Reconhecimento como Patrimônio da Humanidade',
    slug: 'patrimonio-imaterial-unesco',
    period_label: 'Dezembro de 2012',
    year_start: 2012,
    year_end: 2012,
    content: 'O Frevo é proclamado pela UNESCO como Patrimônio Cultural Imaterial da Humanidade, consagrando sua música, dança e tradição coletiva como tesouro do planeta.',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
    source_text: 'UNESCO Heritage Portal',
    source_url: 'https://unesco.org',
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_MAP_POINTS: MapPoint[] = [
  {
    id: 'm1',
    name: 'Paço do Frevo',
    slug: 'paco-do-frevo',
    description: 'Centro de referência cultural, memória, pesquisa e ensino da dança e música do Frevo no coração do Recife Antigo.',
    address: 'Praça do Arsenal da Marinha, s/n - Bairro do Recife, Recife - PE',
    latitude: -8.0617,
    longitude: -34.8711,
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    category: 'Museu / Centro Cultural',
    period_label: 'Inaugurado em 2014',
    source_text: 'Paço do Frevo Oficial',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm2',
    name: 'Sede do Bloco Carnavalesco Misto Vassourinhas',
    slug: 'sede-vassourinhas-recife',
    description: 'Fundado em 1889, uma das agremiações mais antigas e célebres do Carnaval pernambucano, criador do mais famoso hino de frevo de todos os tempos.',
    address: 'Largo do Amparo, Olinda / Recife - PE',
    latitude: -8.0534,
    longitude: -34.8778,
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80',
    category: 'Agremiação Histórica',
    period_label: 'Fundado em 1889',
    source_text: 'Patrimônio Cultural do Recife',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm3',
    name: 'Quatro Cantos de Olinda',
    slug: 'quatro-cantos-olinda',
    description: 'Ponto de encontro lendário das orquestras de rua e dos passistas ladeira acima durante o cortejo do carnaval.',
    address: 'Cruzamento das Ruas Amparo, Prudente de Morais e Bernardo Vieira - Olinda - PE',
    latitude: -7.9996,
    longitude: -34.8488,
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
    category: 'Polo Tradicional',
    period_label: 'Tradição Secular',
    source_text: 'Guia do Carnaval de Olinda',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
